steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/ohamoni-app-repo/ohamoni-app:$COMMIT_SHA",
        ".",
      ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/ohamoni-app-repo/ohamoni-app:$COMMIT_SHA",
      ]
  - id: "apply migrations"
    name: "gcr.io/google-appengine/exec-wrapper"
    entrypoint: "bash"
    args:
      [
        "-c",
        "/buildstep/execute.sh -i gcr.io/$PROJECT_ID/ohamoni-app-repo/ohamoni-app -s $PROJECT_ID:asia-northeast1:hide -e DATABASE_URL=$$PRISMA_DATABASE_URL -- yarn prisma migrate",
      ]
    secretEnv: ["PRISMA_DATABASE_URL"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "ohamoni-app"
      - "--image"
      - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/ohamoni-app-repo/ohamoni-app:$COMMIT_SHA"
      - "--region"
      - "asia-northeast1"
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/ohamoni_prod_database_url/versions/latest
      env: PRISMA_DATABASE_URL
images:
  - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/ohamoni-app-repo/ohamoni-app:$COMMIT_SHA"
