version: '3'
services:
  db:
    image: mysql:8.0 # 2023/06/30 GCPで8系が最新で8.0だったので
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3332:3306
    volumes:
      - ./mysql8/mysql_data:/var/lib/mysql # データの永続化 ホストのディレクトリ:コンテナ内のディレクトリで中身が同期される
      - ./mysql8/conf.d:/etc/mysql/conf.d
  gcloud-tasks-emulator:
    image: ghcr.io/aertje/cloud-tasks-emulator:latest
    command: >
      -host 0.0.0.0 -port 8133
      -queue "projects/dev/locations/asia-northeast1/queues/ohamoni-dev"
    ports:
      - "${TASKS_PORT:-8133}:8133"
