version: '3'
services:
  db:
    image: postgres:15-alpine # 2023/10/31 GCPで15が最新だったので
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5332:5432
    volumes:
      - ./.postgres15/postgres_data:/var/lib/postgresql/data
  gcloud-tasks-emulator:
    image: ghcr.io/aertje/cloud-tasks-emulator:latest
    command: >
      -host 0.0.0.0 -port 8133
      -queue "projects/dev/locations/asia-northeast1/queues/ohamoni-dev"
    ports:
      - "${TASKS_PORT:-8133}:8133"
